
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.HButtonBox hbuttonbox1;

	private global::Gtk.Button novoBotao;

	private global::Gtk.Button abrirBotao;

	private global::Gtk.Button salvarBotao;

	private global::Gtk.Button executarBotao;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView editorCampo;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView saidaCampo;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entradaCampo;

	private global::Gtk.Button okBotao;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Humberto Costa | Ambiente de Desenvolvimento");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.novoBotao = new global::Gtk.Button();
		this.novoBotao.CanFocus = true;
		this.novoBotao.Name = "novoBotao";
		this.novoBotao.UseStock = true;
		this.novoBotao.UseUnderline = true;
		this.novoBotao.Label = "gtk-new";
		this.hbuttonbox1.Add(this.novoBotao);
		global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.novoBotao]));
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.abrirBotao = new global::Gtk.Button();
		this.abrirBotao.CanFocus = true;
		this.abrirBotao.Name = "abrirBotao";
		this.abrirBotao.UseStock = true;
		this.abrirBotao.UseUnderline = true;
		this.abrirBotao.Label = "gtk-open";
		this.hbuttonbox1.Add(this.abrirBotao);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.abrirBotao]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.salvarBotao = new global::Gtk.Button();
		this.salvarBotao.CanFocus = true;
		this.salvarBotao.Name = "salvarBotao";
		this.salvarBotao.UseStock = true;
		this.salvarBotao.UseUnderline = true;
		this.salvarBotao.Label = "gtk-save";
		this.hbuttonbox1.Add(this.salvarBotao);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.salvarBotao]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.executarBotao = new global::Gtk.Button();
		this.executarBotao.CanFocus = true;
		this.executarBotao.Name = "executarBotao";
		this.executarBotao.UseStock = true;
		this.executarBotao.UseUnderline = true;
		this.executarBotao.Label = "gtk-execute";
		this.hbuttonbox1.Add(this.executarBotao);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.executarBotao]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add(this.hbuttonbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.editorCampo = new global::Gtk.TextView();
		this.editorCampo.CanFocus = true;
		this.editorCampo.Name = "editorCampo";
		this.GtkScrolledWindow.Add(this.editorCampo);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w7.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.saidaCampo = new global::Gtk.TextView();
		this.saidaCampo.CanFocus = true;
		this.saidaCampo.Name = "saidaCampo";
		this.saidaCampo.Editable = false;
		this.saidaCampo.CursorVisible = false;
		this.saidaCampo.AcceptsTab = false;
		this.GtkScrolledWindow1.Add(this.saidaCampo);
		this.vbox2.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
		w9.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Entrada de Dados:");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entradaCampo = new global::Gtk.Entry();
		this.entradaCampo.CanFocus = true;
		this.entradaCampo.Name = "entradaCampo";
		this.entradaCampo.IsEditable = true;
		this.entradaCampo.InvisibleChar = '●';
		this.hbox1.Add(this.entradaCampo);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entradaCampo]));
		w11.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.okBotao = new global::Gtk.Button();
		this.okBotao.CanFocus = true;
		this.okBotao.Name = "okBotao";
		this.okBotao.UseStock = true;
		this.okBotao.UseUnderline = true;
		this.okBotao.Label = "gtk-ok";
		this.hbox1.Add(this.okBotao);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.okBotao]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 599;
		this.DefaultHeight = 447;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.novoBotao.Clicked += new global::System.EventHandler(this.OnNovoBotaoClicked);
		this.abrirBotao.Clicked += new global::System.EventHandler(this.OnAbrirBotaoClicked);
		this.salvarBotao.Clicked += new global::System.EventHandler(this.OnSalvarBotaoClicked);
		this.executarBotao.Clicked += new global::System.EventHandler(this.OnExecutarBotaoClicked);
		this.saidaCampo.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnSaidaCampoSizeAllocated);
		this.okBotao.Clicked += new global::System.EventHandler(this.OnOkBotaoClicked);
	}
}
